name: Deploy static site to ARIT-public-repo

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare dist
        env:
          SITE_DIR: .
        run: |
          set -e
          mkdir -p dist
          shopt -s dotglob extglob
          cp -r $SITE_DIR/!(dist|.git|.github) dist/ || true
          touch dist/.nojekyll

      - name: Add CNAME
        run: echo "aritconstruction.com" > dist/CNAME

      - name: Minify HTML/CSS/JS
        run: |
          npm i -g html-minifier-terser clean-css-cli terser
          find dist -name "*.html" -type f -exec sh -c \
            'for f; do html-minifier-terser --collapse-whitespace --remove-comments --remove-optional-tags --minify-css true --minify-js true -o "$f" "$f"; done' sh {} +
          find dist -name "*.css" -type f -exec sh -c \
            'for f; do cleancss -o "$f" "$f"; done' sh {} +
          find dist -name "*.js" -type f -exec sh -c \
            'for f; do terser "$f" -c -m -o "$f"; done' sh {} +

      - name: Show dist tree
        run: |
          echo "----- DIST CONTENTS -----"
          ls -lah dist || true
          echo "----- TOP-LEVEL FILES -----"
          find dist -maxdepth 1 -type f -print
          echo "----- LARGE FILES (>20MB) -----"
          find dist -type f -size +20M -exec du -h {} \; || true

      - name: "Guard: no files over 95MB"
        run: |
          big=$(find dist -type f -size +95M -print | wc -l)
          if [ "$big" -gt 0 ]; then
            echo "Error: Files larger than 95MB found in dist/:"
            find dist -type f -size +95M -print -exec du -h {} \;
            exit 1
          fi

      - name: "Guard: index.html exists"
        run: |
          if [ ! -f dist/index.html ]; then
            echo "Error: dist/index.html not found. Did the copy step point to the right folder?"
            exit 1
          fi

      - name: Deploy to public repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: enionismaili/ARIT-public-repo
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
          single-commit: true
          force: true
